### ISSUE TITLE
Write the templates for all SQL queries

### ISSUE THREAD

**Issue by eashwar** [FAMNM/famnm-website-backend#1]
## Overview
We need templates/the actual thing for the SQL queries that will be used for:

- Creating the tables, with whatever foreign keys are needed
- Inserting entries into the tables.
- Reading entries
- Updating entries
- Deleting entries

The tables are as follows:

### Meetings
Columns: unique id (number), type (string), date (date), description (string)

### People
Columns: uniqname (string), meetings (array of meetingId numbers)

**Comment by AmandaKline** [comment]
I can help with this one unless there's something else you'd like me to work on, or would rather handle it yourself.
